### ISSUE TITLE
hindi strings.xml

### ISSUE THREAD

**Issue by jaagameister** [jaagameister/learning#68]

**Comment by SwatiQP** [comment]
@Dolly-Goyal let's work on it today and tomorrow.

**Comment by KIRINPUTRA** [comment]
2 things:

1, Let's not spend too much time on this yet. We might still have a few structural changes ahead of us — such as enabling Srini to switch up what she say in each context. Pls stay on the "easy" side of the 20-80 Rule for now.

2, Later on, the Hindi localization can serve as a reference point for people working on other Indian localizations. The Indian languages form a cultural cluster, and Hindi gives us the best shot to exchange ideas since almost everybody at Jāga speak Hindi.

**Comment by KIRINPUTRA** [comment]
@rohitacc @Dolly-Goyal @SwatiQP

**Comment by SwatiQP** [comment]
@KIRINPUTRA correct me here if i am wrong, we should stick to english (80) and hindi (20)?

**Comment by KIRINPUTRA** [comment]
(Nothing to do with EN vs HI.) Typically, the first 20% of effort yields like 80% of the results. The last 20% in results — i.e. reaching perfection — takes four times the effort. Please let's stay w/i the first 20% of effort for now. The "geek squad" (inc. myself) will let Y'all know when it's safe to polish your strings and "go for the gold".

**Comment by Dolly-Goyal** [comment]
close
